#!/usr/bin/env python3
"""Prepare pinned OpenCV/YuNet inputs and build arm64 iOS static archives.

Run from any directory; paths are relative to this script's module. Preparation
uses only the Python standard library and works without Xcode. Compilation needs
macOS and an Xcode installation selected by xcode-select.
"""

import argparse
import hashlib
import os
from pathlib import Path
import platform
import plistlib
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
import zipfile


MODULE_DIR = Path(__file__).resolve().parents[1]
OPENCV_URL = "https://github.com/yeatse/opencv-spm/releases/download/4.12.0/opencv2.xcframework.zip"
# Published checksum: https://raw.githubusercontent.com/yeatse/opencv-spm/4.12.0/Package.swift
OPENCV_SHA256 = "13409e99956a74aaee1856c56889c211116fbc8be2bcbe373986ec9e10f536fc"
DEFAULT_ARCHIVE = MODULE_DIR / "build/ios-dependencies/opencv2-4.12.0.xcframework.zip"
MODEL_PATH = MODULE_DIR / "src/jvmSharedMain/resources/com/alpha/facedetection/models/face_detection_yunet_2026may.onnx"
MODEL_SHA256 = "ebafce4e3c118d6554634be5c27ab333b4c047a9a8c3faf1d7cf93101c22f0f0"
MODEL_SIZE = 229738
TARGETS = {
    "iosArm64": ("iphoneos", "arm64-apple-ios13.0", None),
    "iosSimulatorArm64": ("iphonesimulator", "arm64-apple-ios13.0-simulator", "simulator"),
}


class BuildError(Exception):
    """An invalid input or unavailable native build tool."""


def verify_sha256(path, expected):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    if digest.hexdigest() != expected:
        raise BuildError("SHA-256 mismatch for {}: expected {}, got {}".format(path, expected, digest.hexdigest()))


def ensure_archive(path, expected_sha256=OPENCV_SHA256):
    """Never replace an existing cache entry or publish an unverified download."""
    path = Path(path)
    if path.exists():
        verify_sha256(path, expected_sha256)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # A unique temporary file avoids interfering with another target's download.
    with tempfile.TemporaryDirectory(prefix="opencv-download-", dir=path.parent) as temp:
        download = Path(temp) / "archive.zip"
        with urllib.request.urlopen(OPENCV_URL, timeout=120) as response, download.open("wb") as destination:
            shutil.copyfileobj(response, destination, 1024 * 1024)
        verify_sha256(download, expected_sha256)
        if path.exists():
            verify_sha256(path, expected_sha256)
        else:
            os.replace(download, path)


def generate_model_header(model, destination, expected_sha256=MODEL_SHA256, expected_size=MODEL_SIZE):
    """Validate before writing, with stable ASCII formatting and LF newlines."""
    data = Path(model).read_bytes()
    if len(data) != expected_size:
        raise BuildError("YuNet model size mismatch: expected {}, got {}".format(expected_size, len(data)))
    if hashlib.sha256(data).hexdigest() != expected_sha256:
        raise BuildError("YuNet model SHA-256 mismatch")
    lines = ["// Generated by build_ios.py; do not edit.", "#pragma once", "#include <stddef.h>", "", "constexpr unsigned char kYuNetModelBytes[] = {"]
    lines.extend("    " + ", ".join("0x{:02x}".format(value) for value in data[offset:offset + 12]) + "," for offset in range(0, len(data), 12))
    lines.extend(["};", "constexpr size_t kYuNetModelSize = sizeof(kYuNetModelBytes);", ""])
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes("\n".join(lines).encode("ascii"))


def safe_parts(name):
    """Reject ZIP paths with POSIX or Windows traversal/aliasing semantics."""
    if not isinstance(name, str) or not name or name.startswith("/") or "\\" in name or "\x00" in name:
        raise BuildError("Unsafe archive path: {!r}".format(name))
    parts = tuple(name.rstrip("/").split("/"))
    reserved = {"CON", "PRN", "AUX", "NUL"} | {prefix + str(i) for prefix in ("COM", "LPT") for i in range(1, 10)}
    for part in parts:
        if part in ("", ".", "..") or any(c in part for c in ':<>"|?*') or part.endswith((".", " ")) or any(ord(c) < 32 for c in part) or part.split(".")[0].upper() in reserved:
            raise BuildError("Unsafe archive path: {!r}".format(name))
    return parts


def select_library(metadata, target):
    if target not in TARGETS:
        raise BuildError("Unsupported target: {}".format(target))
    if not isinstance(metadata, dict) or not isinstance(metadata.get("AvailableLibraries"), list):
        raise BuildError("Invalid XCFramework Info.plist: missing AvailableLibraries")
    variant = TARGETS[target][2]
    matches = [item for item in metadata["AvailableLibraries"] if isinstance(item, dict)
               and item.get("SupportedPlatform") == "ios"
               and item.get("SupportedPlatformVariant") == variant
               and isinstance(item.get("SupportedArchitectures"), list)
               and "arm64" in item["SupportedArchitectures"]]
    if len(matches) != 1:
        raise BuildError("Expected exactly one arm64 XCFramework slice for {}; found {}".format(target, len(matches)))
    result = matches[0]
    if len(safe_parts(result.get("LibraryIdentifier"))) != 1:
        raise BuildError("Invalid XCFramework LibraryIdentifier")
    library_path = safe_parts(result.get("LibraryPath"))
    if library_path[-1] != "opencv2.framework":
        raise BuildError("Selected library must be an opencv2.framework")
    return result


def materialize_slice(archive, entries, prefix, destination):
    """Resolve ZIP symlinks inside the slice, without creating filesystem links.

    All resolution is against the ZIP's virtual tree. This supports Versions/A
    frameworks on Windows and prevents links from reading or writing outside the
    selected slice. Broken links, cycles and links used as parents are rejected.
    """
    nodes = {(): None}
    for path, entry in entries.items():
        if path[:len(prefix)] != prefix or len(path) == len(prefix):
            continue
        relative = path[len(prefix):]
        nodes[relative] = None if entry.is_dir() else entry
        for length in range(1, len(relative)):
            nodes.setdefault(relative[:length], None)
    children = {path: [] for path, entry in nodes.items() if entry is None}
    for path in nodes:
        if path:
            if path[:-1] not in children:
                raise BuildError("Archive file or symlink is used as a directory")
            children[path[:-1]].append(path[-1])

    def resolve(path, seen=()):
        for length in range(1, len(path) + 1):
            current = path[:length]
            if current not in nodes:
                raise BuildError("Broken framework symlink or missing path: {}".format("/".join(path)))
            entry = nodes[current]
            if entry is not None and stat.S_ISLNK(entry.external_attr >> 16):
                if current in seen or len(seen) >= 64:
                    raise BuildError("Cyclic framework symlink")
                target = archive.read(entry).decode("utf-8")
                if not target or target.startswith("/") or "\\" in target:
                    raise BuildError("Unsafe framework symlink target")
                normalized = list(current[:-1])
                for part in target.split("/"):
                    if part == "..":
                        if not normalized:
                            raise BuildError("Framework symlink escapes selected slice")
                        normalized.pop()
                    elif part not in ("", "."):
                        safe_parts(part)
                        normalized.append(part)
                return resolve(tuple(normalized) + path[length:], seen + (current,))
        return path

    def copy(path, output, ancestors=()):
        resolved = resolve(path)
        if resolved in ancestors:
            raise BuildError("Cyclic framework directory symlink")
        entry = nodes[resolved]
        if entry is None:
            output.mkdir(parents=True, exist_ok=True)
            for name in sorted(children[resolved]):
                copy(resolved + (name,), output / name, ancestors + (resolved,))
        else:
            with archive.open(entry) as source, output.open("wb") as sink:
                shutil.copyfileobj(source, sink, 1024 * 1024)

    copy((), destination)


def extract_framework(archive_path, target, output, expected_sha256=OPENCV_SHA256):
    """Verify the archive and publish only root metadata and the selected slice."""
    verify_sha256(archive_path, expected_sha256)
    with zipfile.ZipFile(archive_path) as archive:
        entries = {}
        folded = set()
        canonical_paths = {}
        for entry in archive.infolist():
            # ZipInfo.filename normalizes backslashes on Windows and truncates
            # NULs; validate the original central-directory name first.
            path = safe_parts(entry.orig_filename)
            key = tuple(part.casefold() for part in path)
            if key in folded:
                raise BuildError("Duplicate or case-colliding archive path")
            folded.add(key)
            for length in range(1, len(path) + 1):
                previous = canonical_paths.setdefault(key[:length], path[:length])
                if previous != path[:length]:
                    raise BuildError("Case-colliding archive directory")
            mode = stat.S_IFMT(entry.external_attr >> 16)
            if mode not in (0, stat.S_IFREG, stat.S_IFDIR, stat.S_IFLNK):
                raise BuildError("Unsupported special file in archive")
            entries[path] = entry
        roots = [path for path in entries if len(path) >= 2 and path[-1] == "Info.plist" and path[-2].endswith(".xcframework")]
        if len(roots) != 1:
            raise BuildError("Expected exactly one XCFramework root Info.plist")
        info_path = roots[0]
        info_bytes = archive.read(entries[info_path])
        library = select_library(plistlib.loads(info_bytes), target)
        identifier = library["LibraryIdentifier"]
        prefix = info_path[:-1] + (identifier,)
        output = Path(output)
        output.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix="opencv-extract-", dir=output) as temp:
            staged = Path(temp) / "opencv2.xcframework"
            staged.mkdir()
            (staged / "Info.plist").write_bytes(info_bytes)
            materialize_slice(archive, entries, prefix, staged / identifier)
            relative_framework = Path(identifier).joinpath(*safe_parts(library["LibraryPath"]))
            framework = staged / relative_framework
            if not (framework / "Headers/core.hpp").is_file() or not (framework / "opencv2").is_file():
                raise BuildError("Selected framework lacks Headers/core.hpp or opencv2 binary")
            published = output / "opencv2.xcframework"
            # Refuse a pre-existing alias before replacing our own output tree.
            if published.is_symlink() or published.resolve().parent != output.resolve():
                raise BuildError("Unsafe existing XCFramework output path")
            if published.exists():
                shutil.rmtree(published)
            os.replace(staged, published)
    return published / relative_framework


def validate_static_archive(path):
    """Require a nonempty, self-contained ar archive, not Mach-O or thin ar."""
    path = Path(path)
    size = path.stat().st_size
    members = 0
    with path.open("rb") as stream:
        if stream.read(8) != b"!<arch>\n":
            raise BuildError("Not a standalone static archive: {}".format(path))
        while stream.tell() < size:
            header = stream.read(60)
            if len(header) != 60 or header[58:] != b"`\n":
                raise BuildError("Invalid static archive member header: {}".format(path))
            try:
                member_size = int(header[48:58])
            except ValueError as error:
                raise BuildError("Invalid static archive member size") from error
            end = stream.tell() + member_size
            if member_size < 0 or end + (member_size % 2) > size:
                raise BuildError("Truncated static archive: {}".format(path))
            stream.seek(end + (member_size % 2))
            members += 1
    if not members:
        raise BuildError("Empty static archive: {}".format(path))


def run_command(argv):
    try:
        return subprocess.run(argv, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True).stdout.strip()
    except FileNotFoundError as error:
        raise BuildError("xcrun unavailable; install Xcode and select it with xcode-select") from error
    except subprocess.CalledProcessError as error:
        raise BuildError("Native build command failed: {}\n{}".format(argv[0], (error.stderr or "").strip())) from error


def build_native(module, target, output, framework):
    if platform.system() != "Darwin":
        raise BuildError("Native iOS compilation requires macOS (Darwin) and Xcode; use --prepare-only on this host")
    sdk, triple, _ = TARGETS[target]
    output = Path(output)
    module = Path(module)
    framework = Path(framework)
    sdk_path = run_command(["xcrun", "--sdk", sdk, "--show-sdk-path"])
    if not sdk_path:
        raise BuildError("xcrun returned an empty SDK path")
    source = module / "src/iosMain/cpp/FaceDetectionBridge.cpp"
    header = module / "src/nativeInterop/cinterop/FaceDetectionBridge.h"
    if not source.is_file() or not header.is_file():
        raise BuildError("Missing FaceDetectionBridge.cpp or FaceDetectionBridge.h")
    output.mkdir(parents=True, exist_ok=True)
    bridge_object = output / "bridge.o"
    bridge_archive = output / "libShowcaseFaceDetection.a"
    opencv_archive = output / "libopencv2.a"
    binary = framework / "opencv2"
    architectures = run_command(["xcrun", "lipo", "-archs", str(binary)]).split()
    if "arm64" not in architectures:
        raise BuildError("Selected OpenCV binary does not contain arm64")
    with binary.open("rb") as stream:
        magic = stream.read(4)
    fat = magic in (b"\xca\xfe\xba\xbe", b"\xbe\xba\xfe\xca", b"\xca\xfe\xba\xbf", b"\xbf\xba\xfe\xca")
    if fat or len(architectures) > 1:
        run_command(["xcrun", "lipo", str(binary), "-thin", "arm64", "-output", str(opencv_archive)])
    else:
        shutil.copyfile(binary, opencv_archive)
    validate_static_archive(opencv_archive)
    run_command(["xcrun", "--sdk", sdk, "clang++", "-std=c++17", "-O2", "-fvisibility=hidden", "-target", triple, "-isysroot", sdk_path,
                 "-I", str(header.parent), "-I", str(output / "generated"), "-F", str(framework.parent),
                 "-c", str(source), "-o", str(bridge_object)])
    run_command(["xcrun", "libtool", "-static", "-o", str(bridge_archive), str(bridge_object)])
    validate_static_archive(bridge_archive)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=tuple(TARGETS), required=True)
    parser.add_argument("--output", type=Path, required=True, help="Absolute target-specific output directory")
    parser.add_argument("--prepare-only", action="store_true", help="Verify/extract dependencies and generate the model header without Xcode")
    parser.add_argument("--archive", type=Path, default=DEFAULT_ARCHIVE, help="Pinned OpenCV ZIP cache (downloaded if missing)")
    args = parser.parse_args(argv)
    if not args.output.is_absolute():
        parser.error("--output must be an absolute directory")
    try:
        if not args.prepare_only and platform.system() != "Darwin":
            raise BuildError("Native iOS compilation requires macOS (Darwin) and Xcode; use --prepare-only on this host")
        generate_model_header(MODEL_PATH, args.output / "generated/YuNetModelBytes.h", MODEL_SHA256, MODEL_SIZE)
        ensure_archive(args.archive, OPENCV_SHA256)
        framework = extract_framework(args.archive, args.target, args.output, OPENCV_SHA256)
        if args.prepare_only:
            print("Prepared {}: {}".format(args.target, args.output))
        else:
            build_native(MODULE_DIR, args.target, args.output, framework)
            print("Built {}: {} and {}".format(args.target, args.output / "libShowcaseFaceDetection.a", args.output / "libopencv2.a"))
        return 0
    except (BuildError, OSError, urllib.error.URLError, zipfile.BadZipFile, plistlib.InvalidFileException, ValueError) as error:
        print("error: {}".format(error))
        return 1


if __name__ == "__main__":
    sys.exit(main())
