#include "FaceDetectionBridge.h"

// Generated by the native build from the checksum-validated bundled ONNX model.
// Defines kYuNetModelBytes and kYuNetModelSize in the global namespace.
#include "YuNetModelBytes.h"

#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/objdetect/face.hpp>

#include <algorithm>
#include <cmath>
#include <limits>
#include <mutex>
#include <vector>

namespace {

// Keep these values and the geometry checks aligned with common FaceGeometry.kt.
constexpr float kScoreThreshold = 0.6f;
constexpr float kNmsThreshold = 0.3f;
constexpr int kTopK = 5000;
constexpr int kResultColumns = 15;
constexpr int kMaxEdge = 640;

struct DetectorState {
    std::mutex mutex;
    cv::Ptr<cv::FaceDetectorYN> detector;
};

cv::Size detectionSize(int width, int height) {
    const double scale = std::min(1.0, static_cast<double>(kMaxEdge) / std::max(width, height));
    return cv::Size(
        std::max(1, static_cast<int>(std::lround(width * scale))),
        std::max(1, static_cast<int>(std::lround(height * scale))));
}

bool isVisibleFace(const float *row, int width, int height) {
    if (!std::isfinite(row[14]) || row[14] < kScoreThreshold) {
        return false;
    }
    for (int index = 0; index < 4; ++index) {
        if (!std::isfinite(row[index])) {
            return false;
        }
    }
    const float imageWidth = static_cast<float>(width);
    const float imageHeight = static_cast<float>(height);
    const float left = std::clamp(row[0] / imageWidth, 0.0f, 1.0f);
    const float top = std::clamp(row[1] / imageHeight, 0.0f, 1.0f);
    const float right = std::clamp((row[0] + row[2]) / imageWidth, 0.0f, 1.0f);
    const float bottom = std::clamp((row[1] + row[3]) / imageHeight, 0.0f, 1.0f);
    return right > left && bottom > top;
}

} // namespace

extern "C" int showcase_face_inspect(const unsigned char *encoded, size_t length) {
    try {
        // OpenCV represents the encoded buffer's length with an int.
        if (encoded == nullptr || length == 0 ||
            length > static_cast<size_t>(std::numeric_limits<int>::max())) {
            return SHOWCASE_FACE_INDETERMINATE;
        }

        // Construction, model loading, setInputSize, and inference all stay inside
        // the exception boundary. Every factory instance shares this process cache.
        static DetectorState state;
        const std::lock_guard<std::mutex> lock(state.mutex);
        const std::vector<unsigned char> bytes(encoded, encoded + length);
        cv::Mat input = cv::imdecode(bytes, cv::IMREAD_COLOR | cv::IMREAD_IGNORE_ORIENTATION);
        if (input.empty() || input.cols <= 0 || input.rows <= 0) {
            return SHOWCASE_FACE_INDETERMINATE;
        }

        const cv::Size size = detectionSize(input.cols, input.rows);
        if (input.size() != size) {
            cv::Mat resized;
            cv::resize(input, resized, size, 0.0, 0.0, cv::INTER_LINEAR);
            input = resized;
        }

        if (state.detector.empty()) {
            const std::vector<unsigned char> model(kYuNetModelBytes, kYuNetModelBytes + kYuNetModelSize);
            const std::vector<unsigned char> config;
            state.detector = cv::FaceDetectorYN::create(
                "onnx", model, config, cv::Size(320, 320),
                kScoreThreshold, kNmsThreshold, kTopK);
            if (state.detector.empty()) {
                return SHOWCASE_FACE_INDETERMINATE;
            }
        }

        state.detector->setInputSize(input.size());
        cv::Mat faces;
        // In OpenCV 4.12.0, 1 means inference completed (even with zero faces).
        if (state.detector->detect(input, faces) != 1) {
            return SHOWCASE_FACE_INDETERMINATE;
        }
        if (faces.empty()) {
            return SHOWCASE_FACE_NO_FACE;
        }
        if (faces.dims != 2 || faces.cols < kResultColumns || faces.type() != CV_32FC1) {
            return SHOWCASE_FACE_INDETERMINATE;
        }
        for (int index = 0; index < faces.rows; ++index) {
            if (isVisibleFace(faces.ptr<float>(index), input.cols, input.rows)) {
                return SHOWCASE_FACE_DETECTED;
            }
        }
        return SHOWCASE_FACE_NO_FACE;
    } catch (...) {
        return SHOWCASE_FACE_INDETERMINATE;
    }
}
